sudo: required
dist: focal  # ou bionic pour Ubuntu 18.04

language: node_js
node_js:
  - "18"

services:
  - docker

before_install:
  - npm install -g npm@latest
  - docker build -t amir/docker-react -f Dockerfile.dev .

install:
  - npm ci

script:
  - docker run -e CI=true amir/docker-react npm run test -- --coverage
