---
language: ruby
rvm:
  - 2.7.6

sudo: required

services:
  - docker

before_install: 
  - docker build -t amir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amir/docker-react npm run test -- --coverage