language: ruby
rvm:
  - 2.7.6
  
sudo: required

services:
  - docker

before_install:
  - docker build -t amir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amir/docker-react npm run test -- --coverage

# Add empty install step to bypass default bundle install
install: true

# Add empty before_script step to ensure no default actions are performed
before_script: []
