sudo: required

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - docker build -t amir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amir/docker-react npm run test -- --coverage

